baseURL: /
languageCode: en-us
title: Hugo Persona
params:
  name: "Hugo Persona"
  mastodon:
  gtag:
  description:
  title:
  keywords:
build:
  writeStats: true
  useResourceCacheWhen: fallback
paginate: 5
